name: Update themes.txt with Commit Message
on:
  push:
    paths:
      - 'tokens/tokens.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update themes.txt
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          echo [$commit_message] > tokens/themes.txt
          git add tokens/themes.txt
          git config user.name "mineclover"
          git config user.email "mineclover@naver.com"
          git commit -m "Update theme.json with commit message" --no-verify
          git push
